### ISSUE TITLE
Package domain in order FK CommandAcceptanceException

### ISSUE THREAD

**Issue by sujjangOvO** [sujjangOvO/mk_springboot#15]
GenerationTarget encountered exception accepting command : Error executing DDL "
    alter table orders 
       add constraint FKmma24ia1oquc8riqmi0jahfq0 
       foreign key (order_id) 
       references package (package_id)" via JDBC Statement

org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "
    alter table orders 
       add constraint FKmma24ia1oquc8riqmi0jahfq0 
       foreign key (order_id) 
       references package (package_id)" via JDBC Statement

Caused by: java.sql.SQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`MOONKEY`.`#sql-86b81_8`, CONSTRAINT `FKmma24ia1oquc8riqmi0jahfq0` FOREIGN KEY (`order_id`) REFERENCES `package` (`package_id`))

**Comment by asuan99** [comment]
JPA Association rule [reference](https://jaegukim.github.io/posts/joincolumn-vs-mappedby-orm%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%A0%EB%95%8C-%EC%A3%BC%EC%9D%98%ED%95%A0%EC%A0%90/)
